// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "go-template/web/view/components"

var menuItems = []struct {
	Section string
	Items   []components.MenuItem
}{
	{
		Items: []components.MenuItem{
			{Label: "Home", Icon: "home"},
			{Label: "Parking Lots", Icon: "parking"},
			{Label: "Bookings", Icon: "calendar"},
			{Label: "Parker Accounts", Icon: "users"},
			{Label: "Entries & Exits", Icon: "entries"},
			{Label: "Users", Icon: "user"},
			{Label: "RFID Tags", Icon: "rfid"},
			{Label: "Settings", Icon: "settings", SubItems: []components.MenuItem{
				{Label: "General", Icon: "general"},
				{Label: "Security", Icon: "security"},
				{Label: "Notifications", Icon: "notifications"},
				{Label: "Billing", Icon: "billing"},
			}},
			{Label: "Settings1", Icon: "settings", SubItems: []components.MenuItem{
				{Label: "General", Icon: "general"},
			}},
		},
	},
}

func sidebar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"py-2 fixed flex flex-col h-screen bg-gray-800 text-white transition-all duration-300 ease-in-out overflow-y-auto overflow-x-hidden w-64 [#sidebar-toggle:checked~&amp;]:w-16\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.SidebarHeader().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, section := range menuItems {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"px-3\"><div class=\"text-sm font-medium text-gray-400 mb-2 transition-opacity duration-300 [#sidebar-toggle:checked~*_&amp;]:opacity-0\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(section.Section)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/view/sidebar.templ`, Line: 37, Col: 22}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, item := range section.Items {
				templ_7745c5c3_Err = components.NavigationItem(item).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"mt-auto\"><div class=\"text-sm font-medium text-gray-400 px-3 mb-2 transition-all duration-300 overflow-hidden [#sidebar-toggle:checked~*_&amp;]:w-0 [#sidebar-toggle:checked~*_&amp;]:opacity-0 [#sidebar-toggle:checked~*_&amp;]:invisible\"></div><div class=\"flex items-center cursor-pointer hover:bg-gray-700/50 rounded-lg\"><div class=\"w-16 flex items-center justify-center\"><img class=\"w-8 h-8 rounded-lg\" src=\"https://avatars.githubusercontent.com/u/124599\" alt=\"User avatar\"></div><div class=\"flex-1 flex items-center transition-all duration-300 overflow-hidden [#sidebar-toggle:checked~*_&amp;]:w-0 [#sidebar-toggle:checked~*_&amp;]:opacity-0 [#sidebar-toggle:checked~*_&amp;]:invisible\"><div class=\"flex flex-col\"><div class=\"text-sm whitespace-nowrap\">shadcn</div><div class=\"text-xs text-gray-400 whitespace-nowrap\">m@example.com</div></div><div class=\"ml-auto pr-4\"><svg class=\"w-4 h-4 text-gray-400\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M19 9l-7 7-7-7\"></path></svg></div></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
