version: "3"
vars:
  FINAL_NAME: go-template
tasks:
  dev:
    deps:
      - "tailwind"
      - "live-reload" 
  build:
    deps:
      - "install-dependencies"
    cmds:
      - "rm -rf ./dist/*"
      - "go build -o dist/{{.FINAL_NAME}} ."
  migration-create: #task migration-create -- init
    desc: "usage: task migration-create -- name_of_migration"
    cmds:
      - "goose -dir migrations create {{.CLI_ARGS}} sql"
  install-dependencies:
    internal: true
    deps:
      - "node-dependencies"
      - "go-dependencies"    
  install:
    desc: "install dependencies"
    deps:
      - goose
      - air
      - node-dependencies
      - go-dependencies
  goose:
    internal: true
    cmds:
      - "go install github.com/pressly/goose/v3/cmd/goose@latest"
  air:
    internal: true
    cmds:
      - "go install github.com/air-verse/air@latest"  
  node-dependencies:
    internal: true
    cmds:
      - "npm install"  
  go-dependencies:
    internal: true
    cmds:
      - "go mod tidy"      
  tailwind:
    internal: true
    cmds:
      - "npm run dev"    
  live-reload:
    internal: true
    cmds:
      - "air"        