// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func SidebarHeader() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"px-2\"><div class=\"flex items-center\"><div class=\"w-16 h-16 flex items-center justify-center\"><div class=\"w-10 h-10 bg-blue-600 rounded-lg flex items-center justify-center\"><svg class=\"w-6 h-6\" fill=\"currentColor\" viewBox=\"0 0 20 20\"><path d=\"M2 4.75A2.75 2.75 0 014.75 2h10.5A2.75 2.75 0 0118 4.75v10.5A2.75 2.75 0 0115.25 18H4.75A2.75 2.75 0 012 15.25V4.75z\"></path></svg></div></div><div class=\"flex-1 transition-all duration-300 overflow-hidden [#sidebar-toggle:checked~*_&amp;]:w-0 [#sidebar-toggle:checked~*_&amp;]:opacity-0 [#sidebar-toggle:checked~*_&amp;]:invisible\"><div class=\"text-lg font-semibold whitespace-nowrap\">Cubework</div><div class=\"text-sm text-gray-400 whitespace-nowrap\">Parking Admin</div></div><div class=\"flex items-center [#sidebar-toggle:checked~*_&amp;]:hidden\"><label for=\"sidebar-toggle\" class=\"cursor-pointer px-2 hover:bg-gray-700 rounded-lg\" x-data @click=\"document.querySelectorAll(&#39;.menu-item-checkbox&#39;).forEach(checkbox =&gt; checkbox.checked = false);\"><svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M11 19l-7-7 7-7m8 14l-7-7 7-7\"></path></svg></label></div></div><div class=\"hidden [#sidebar-toggle:checked~*_&amp;]:block\"><div class=\"flex justify-center\"><div class=\"w-16 h-16 flex items-center justify-center\"><label for=\"sidebar-toggle\" class=\"cursor-pointer p-2 hover:bg-gray-700 rounded-lg\"><svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M13 5l7 7-7 7M5 5l7 7-7 7\"></path></svg></label></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
